[versions]
kotlin = "1.9.23"
jetbrainsCompose = "1.6.2"
androidGradlePlugin = "8.4.0"
activityCompose = "1.9.0"
kDeviceInfo = "0.0.7"
composeNavigation = "2.8.0-alpha02"


[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
kDeviceInfo = { module = "io.github.swapnil-musale:KDeviceInfo", version.ref = "kDeviceInfo" }
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "composeNavigation" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
